### ISSUE TITLE
What Changes from Movies 1 ? 

### ISSUE THREAD

**Issue by yudhir** [skydoves/TheMovies2#1]

**Comment by skydoves** [comment]
@yudhir 
Hi, there is not much architectural difference between TheMovies2 and [TheMovies](https://github.com/skydoves/themovies). 
Kotlin based MVVM architecture with data-binding and repository pattern.
The difference is, TheMovies2's architecture is implemented with __coroutines__ and used __koin__ for constructing dependency injection instead of dagger2.
And [TheMovies - ApiResponse](https://github.com/skydoves/TheMovies/blob/master/app/src/main/java/com/skydoves/themovies/api/ApiResponse.kt) / [TheMovies2 - ApiResponse](https://github.com/skydoves/TheMovies2/blob/master/app/src/main/java/com/skydoves/themovies2/api/ApiResponse.kt) model is different from each other.
Also removed mappers or something small things.
